### PR TITLE
Fix outdated node.js warnings

### PR DESCRIPTION
**Pull request by gruenich**
Update actions checkout, upload-artifact, download-artifact to version 4. The latter two are based on an outdated node.js version

### CODE REVIEW

**Comment by gruenich** [comment]
@SoilRos I was not able to test this automatically. Can you run this with my changes?

**Comment by SoilRos** [comment]
Sorry, I really don't know how to do this ¯\_(ツ)_/¯. I just added you to the dune namespace, I guess that should give you enough access rights to write directly into this repository.

**Comment by gruenich** [comment]
I am going to merge and run a workflow manually. If I find issues, I fix them or revert these changes.

**Comment by gruenich** [comment]
Worked, and all warnings are gone https://github.com/dune-project/dune-testpypi/actions/runs/7773760945

**Pull request merged**
